name: presence_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-225.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.19.1
  firebase_auth: 3.4.1
  cloud_firestore: 3.2.1
  firebase_storage: 10.3.1
  convex_bottom_bar: 3.0.0
  image_picker: ^0.8.5+3
  xid: 1.0.7
  geolocator: 9.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

