// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClLGZyKdnou1Bwlq_93YDgKihN9K39Pd0',
    appId: '1:478974605311:web:22156ed0757484a58f59ca',
    messagingSenderId: '478974605311',
    projectId: 'presence-5cd95',
    authDomain: 'presence-5cd95.firebaseapp.com',
    storageBucket: 'presence-5cd95.appspot.com',
    measurementId: 'G-7PRLKGXPJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA07slFl3uYK-ktfNe1iJ6cPQs963LWOe4',
    appId: '1:478974605311:android:e28c04295b9d787d8f59ca',
    messagingSenderId: '478974605311',
    projectId: 'presence-5cd95',
    storageBucket: 'presence-5cd95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOV4bBDX38tVR3Y8MUCrJWo3m9yyzzvUQ',
    appId: '1:478974605311:ios:11bb9c37c5f0d54c8f59ca',
    messagingSenderId: '478974605311',
    projectId: 'presence-5cd95',
    storageBucket: 'presence-5cd95.appspot.com',
    iosClientId: '478974605311-7e5396gjk6negseutorf6kkll8jq0c7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOV4bBDX38tVR3Y8MUCrJWo3m9yyzzvUQ',
    appId: '1:478974605311:ios:11bb9c37c5f0d54c8f59ca',
    messagingSenderId: '478974605311',
    projectId: 'presence-5cd95',
    storageBucket: 'presence-5cd95.appspot.com',
    iosClientId: '478974605311-7e5396gjk6negseutorf6kkll8jq0c7u.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApps',
  );
}
